# Written by Rain CongJyu Chen

echo -e "Welcome to \033[34;1mRain's Arch Linux\033[0m! Poweroff command is \033[31;1mNOT ALLOWED\033[0m."

autoload -U promptinit
autoload -U colors && colors
autoload -U compinit

PROMPT="[%{$fg[magenta]%}%n%{$reset_color%}@%{$fg[magenta]%}%m %{$fg[cyan]%}%1~%{$reset_color%}]%# "

export CLICOLOR=Yes
export LSCOLORS=ExGxFxdaCxDaDahbadacec

alias ls="ls --color"

plugins=(git zsh-autosuggestions zsh-autocomplete zsh-syntax-highlighting)
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export NEMU_HOME=/home/rainchen/Coding/ics2022/nemu
export AM_HOME=/home/rainchen/Coding/ics2022/abstract-machine
export NPC_HOME=/home/rainchen/Coding/ics2022/npc

# export https_proxy=http://192.168.15.145:7890 http_proxy=http://192.168.15.145:7890 all_proxy=socks5://192.168.15.145:7890

