# Colors (Tokyo Night)
# Source https//github.com/zatchheems/tokyo-night-alacritty-theme

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black   = '#424765'
red     = '#e67d8f'
green   = '#63b29c'
yellow  = '#d8b072'
blue    = '#83a0ec'
magenta = '#b59bf0'
cyan    = '#64cae5'
white   = '#c1c9f1'

# Bright colors
[colors.bright]
black   = '#424765'
red     = '#e67d8f'
green   = '#63b29c'
yellow  = '#d8b072'
blue    = '#83a0ec'
magenta = '#b59bf0'
cyan    = '#64cae5'
white   = '#c1c9f1'

[cursor.style]
shape = "Block"

[font]
size = 16

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[window]
dimensions = {columns = 120, lines = 30}
opacity = 0.9
blur = true
